Internal Table Representation
CI functions updated
basic string table representations
select function for columns and some table metrics
---
Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/maven.yaml b/.github/workflows/maven.yaml
--- a/.github/workflows/maven.yaml
+++ b/.github/workflows/maven.yaml
@@ -16,6 +16,11 @@ jobs:
       - name: Format Code
         run: |
           mvn formatter:format
+          git config user.name github-actions
+          git config user.email github-actions@github.com 
+          git add .
+          git commit -m "Formatted Project" || echo "No commit required"
+          git push
       - name: Compile and Test with Maven 
         run: | 
           mvn --batch-mode --update-snapshots verify
